# Generated by Django 4.2.3 on 2023-07-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('no_of_floor', models.IntegerField(default=1)),
                ('no_of_elevators', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.IntegerField()),
                ('current_floor', models.IntegerField(default=1)),
                ('is_operational', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[(1, 'UP'), (-1, 'DOWN'), (0, 'STANDING\xa0STILL')], default=0, max_length=1)),
                ('door_status', models.CharField(choices=[(1, 'CLOSE'), (0, 'OPEN')], default=0, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elevator_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevatorsystem')),
            ],
        ),
    ]
