# Generated by Django 4.2.3 on 2023-07-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_floor', models.IntegerField()),
                ('to_floor', models.IntegerField()),
                ('is_serviced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
        ),
    ]
