# Generated by Django 4.2.3 on 2023-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_elevatorrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='direction',
            field=models.CharField(choices=[('Upward', 'Upward'), ('Downward', 'Downward'), ('STANDING STILL', 'STANDING STILL')], default='STANDING STILL', max_length=20),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='door_status',
            field=models.CharField(choices=[('CLOSE', 'CLOSE'), ('OPEN', 'OPEN')], default='OPEN', max_length=10),
        ),
    ]
